{% set version = "3.0.0" %}
{% set gomodule = "github.com/errata-ai/vale" %}

package:
  name: vale
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64dce5b3c95e8390aa0b130a7da2637ab22a1b4afd16c411fba79969b1c9c968
  patches:
    - 0000-use-conda-prefix.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}  # [not osx]
    - posix  # [win]
    - go-licenses
  host: []
  run: []

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale --version
    - vale --help
    - vale --version | grep -iE "{{ version.replace(".", "\.") }}"
    - vale ls-dirs
    # verify unix paths
    - mkdir -p "${CONDA_PREFIX}/share/vale/styles"     # [unix]
    - vale ls-dirs | grep "${CONDA_PREFIX}/share"      # [unix]
    - mkdir -p "${CONDA_PREFIX}/etc/vale"              # [unix]
    - touch "${CONDA_PREFIX}/etc/vale/.vale.ini"       # [unix]
    - vale ls-dirs | grep "${CONDA_PREFIX}/etc"        # [unix]
    # verify win paths (sorta)
    - md "%CONDA_PREFIX%\share\vale\styles"            # [win]
    - md "%CONDA_PREFIX%\etc\vale"                     # [win]
    - type "#" >> "%CONDA_PREFIX%\etc\vale\.vale.ini"  # [win]
    - vale ls-dirs

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE
    - license-files/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  dev_url: https://{{ gomodule }}
  doc_url: https://vale.sh/docs

extra:
  recipe-maintainers:
    - bollwyvl
