{% set version = "2.28.1" %}
{% set gomodule = "github.com/errata-ai/vale" %}

package:
  name: vale
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: db8ba14266e026dbbefcd6495e9095a41434e599c109310a6f493a6025a5a42f

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - posix  # [win]
    - go-licenses
  host: []
  run: []

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale --version
    - vale --help
    - vale --version | grep -iE "{{ version.replace(".", "\.") }}"

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE
    - license-files/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  dev_url: https://{{ gomodule }}
  doc_url: https://vale.sh/docs

extra:
  recipe-maintainers:
    - bollwyvl
