{% set version = "3.5.0" %}
{% set gomodule = "github.com/errata-ai/vale" %}


package:
  name: vale
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 13a3b0ef4ba9f0e89f663d7f6ba65facd2fca37333e97512c03ac807e413afe0
  patches:
    - 0000-use-conda-prefix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}          # [unix]
    - {{ compiler("cxx") }}        # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ compiler("m2w64_cxx") }}  # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler("go-cgo") }}
    - go-cgo >=1.21
    - go-licenses
    - posix  # [win]
  host: []
  run: []

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale --version
    - vale --help
    - vale --version | grep -iE "{{ version.replace(".", "\.") }}"
    - vale ls-dirs
    # verify unix paths
    - mkdir -p "${CONDA_PREFIX}/share/vale/styles"        # [unix]
    - vale ls-dirs | grep "${CONDA_PREFIX}/share"         # [unix]
    - mkdir -p "${CONDA_PREFIX}/etc/vale"                 # [unix]
    - touch "${CONDA_PREFIX}/etc/vale/.vale.ini"          # [unix]
    - vale ls-dirs | grep "${CONDA_PREFIX}/etc"           # [unix]
    # verify win paths (sorta)
    - md "%CONDA_PREFIX%\share\vale\styles"               # [win]
    - md "%CONDA_PREFIX%\etc\vale"                        # [win]
    - echo "TODO" >> "%CONDA_PREFIX%\etc\vale\.vale.ini"  # [win]
    - vale ls-dirs

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE
    - license-files/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  dev_url: https://{{ gomodule }}
  doc_url: https://vale.sh/docs

extra:
  recipe-maintainers:
    - bollwyvl
